# Generated by Django 5.2 on 2025-04-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('personality', models.CharField(max_length=200)),
                ('story', models.TextField()),
                ('vaccinated', models.BooleanField(default=False)),
                ('disability', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('pet_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=10)),
            ],
        ),
    ]
