# Generated by Django 4.2 on 2025-04-15 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('hospital', models.CharField(blank=True, max_length=100)),
                ('amount_needed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_raised', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_cases', to='myapp.pet')),
            ],
        ),
    ]
