# Generated by Django 4.2 on 2025-04-16 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_donationrequest_product_rename_story_pet_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('hospital', models.CharField(blank=True, max_length=100)),
                ('amount_needed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_raised', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='description',
            new_name='story',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='is_adopted',
        ),
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='disability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='personality',
            field=models.CharField(default=5, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pets/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=10),
        ),
        migrations.DeleteModel(
            name='DonationRequest',
        ),
        migrations.AddField(
            model_name='donationcase',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_cases', to='myapp.pet'),
        ),
    ]
