# Generated by Django 4.2 on 2025-04-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_donationcase_rename_description_pet_story_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcase',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='donations/'),
        ),
    ]
