# Generated by Django 4.2 on 2025-04-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_donationcase_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='detail',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
