# Generated by Django 4.2 on 2025-04-16 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_pet_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='story',
        ),
    ]
