# Generated by Django 4.2 on 2025-04-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_pet_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='story',
            field=models.TextField(blank=True),
        ),
    ]
