# Generated by Django 4.2 on 2025-05-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_delete_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_we_do_title', models.CharField(default='What we do?', max_length=100)),
                ('what_we_do_content', models.TextField(default='At PawPal, we rescue, care for and rehome stray dogs and cats.')),
                ('what_we_do_content2', models.TextField(default='We work with kind-hearted volunteers and loving adopters to give every furry friend a second chance at life.')),
                ('tagline', models.TextField(default="From street to sofa — we're here for every paw. 🐾")),
                ('why_we_do_title', models.CharField(default='Why we do it?', max_length=100)),
                ('why_we_do_content', models.TextField(default='We believe every dog and cat deserves love, safety, and a place to call home. No paw should be left behind.')),
                ('why_we_do_content2', models.TextField(default="We do this because they can't ask for help — but we can help them. ❤️")),
            ],
            options={
                'verbose_name': 'About Us Content',
                'verbose_name_plural': 'About Us Content',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('content', models.TextField(blank=True)),
                ('is_new', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='1212312121', max_length=20)),
                ('opening_hours', models.TextField(default='mon - fri (9:00 - 18:00)')),
                ('closing_days', models.CharField(default='close every 2nd sun', max_length=100)),
                ('description', models.TextField(default='เราเป็นองค์กรที่ช่วยเหลือสุนัขและแมวจรจัดให้ได้รับความรักและการดูแลอย่างดีที่สุด')),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='PetStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats_title', models.CharField(default='Hope in Numbers', max_length=100)),
                ('treated_count', models.IntegerField(default=200)),
                ('treated_label', models.CharField(default='Sick and injured animals treated', max_length=100)),
                ('adopted_count', models.IntegerField(default=99)),
                ('adopted_label', models.CharField(default='Animals adopted to new homes', max_length=100)),
                ('neutered_count', models.IntegerField(default=112)),
                ('neutered_label', models.CharField(default='Animals neutered and vaccinated', max_length=100)),
            ],
            options={
                'verbose_name': 'Pet Statistics',
                'verbose_name_plural': 'Pet Statistics',
            },
        ),
    ]
