# Generated by Django 4.2 on 2025-05-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourmodel',
            name='your_url',
            field=models.URLField(max_length=5000),
        ),
    ]
