# Generated by Django 4.2 on 2025-05-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_yourmodel_your_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
    ]
