# Generated by Django 4.2 on 2025-05-06 03:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0020_userfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_pets', to=settings.AUTH_USER_MODEL),
        ),
    ]
