# Generated by Django 4.2 on 2025-05-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_message_conversation_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('subdistrict', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('household', models.TextField(blank=True, null=True)),
                ('other_pets', models.TextField(blank=True, null=True)),
                ('property_description', models.TextField(blank=True, null=True)),
                ('job_working_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('apply_date', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('pets', models.ManyToManyField(related_name='applications', to='myapp.pet')),
            ],
        ),
    ]
