# Generated by Django 4.2 on 2025-05-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_adoptionapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='is_adopted',
            field=models.BooleanField(default=False),
        ),
    ]
