# Generated by Django 4.2 on 2025-05-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_adoptionapplication_is_adopted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='is_adopted',
        ),
        migrations.AddField(
            model_name='pet',
            name='is_adopted',
            field=models.BooleanField(default=False),
        ),
    ]
