# Generated by Django 4.2 on 2025-05-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_remove_adoptionapplication_is_adopted_pet_is_adopted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
