# Generated by Django 4.2 on 2025-05-09 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0027_alter_pet_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcase',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.CreateModel(
            name='DonationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('slip_image', models.ImageField(upload_to='donation_slips/')),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('donation_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='myapp.donationcase')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
