# Generated by Django 4.2 on 2025-05-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_donationcase_qr_code_image_donationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promptpay_qr_code', models.ImageField(blank=True, null=True, upload_to='site_settings/qr_codes/', verbose_name='PromptPay QR Code Image')),
            ],
            options={
                'verbose_name': 'Donation Settings',
                'verbose_name_plural': 'Donation Settings',
            },
        ),
        migrations.RemoveField(
            model_name='donationcase',
            name='qr_code_image',
        ),
    ]
