# Generated by Django 4.2 on 2025-05-10 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_donationsettings_remove_donationcase_qr_code_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrecord',
            name='donation_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='myapp.donationcase'),
        ),
    ]
