# Generated by Django 4.2 on 2025-05-10 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_donationrecord_donation_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pets/additional/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image.', max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='myapp.pet')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
