# Generated by Django 5.2.1 on 2025-05-11 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_petimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoptionapplication',
            options={'ordering': ['-apply_date'], 'verbose_name': 'คำขอรับเลี้ยง', 'verbose_name_plural': 'คำขอรับเลี้ยงทั้งหมด'},
        ),
        migrations.AlterModelOptions(
            name='donationrecord',
            options={'ordering': ['-donated_at'], 'verbose_name': 'รายการบริจาค', 'verbose_name_plural': 'รายการบริจาคทั้งหมด'},
        ),
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ (Pending)'), ('approved', 'อนุมัติแล้ว (Approved)'), ('rejected', 'ถูกปฏิเสธ (Rejected)'), ('under_review', 'กำลังตรวจสอบ (Under Review)')], default='pending', max_length=20, verbose_name='สถานะคำขอ'),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='address',
            field=models.CharField(max_length=255, verbose_name='ที่อยู่'),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='apply_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่ยื่นคำขอ'),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='อำเภอ/เขต'),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมล'),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='ชื่อจริง'),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='household',
            field=models.TextField(blank=True, null=True, verbose_name='บุคคลในครัวเรือน'),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='job_working_hours',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='อาชีพและเวลาทำงาน'),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='นามสกุล'),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='motivation',
            field=models.TextField(blank=True, null=True, verbose_name='เหตุผลที่ต้องการรับเลี้ยง'),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='other_pets',
            field=models.TextField(blank=True, null=True, verbose_name='สัตว์เลี้ยงอื่นๆ (ถ้ามี)'),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='pets',
            field=models.ManyToManyField(related_name='applications', to='myapp.pet', verbose_name='สัตว์เลี้ยงที่ขอรับเลี้ยง'),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทรศัพท์'),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัสไปรษณีย์'),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='property_description',
            field=models.TextField(blank=True, null=True, verbose_name='รายละเอียดที่พักอาศัย'),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='จังหวัด'),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='subdistrict',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ตำบล/แขวง'),
        ),
        migrations.AlterField(
            model_name='donationrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวนเงิน'),
        ),
        migrations.AlterField(
            model_name='donationrecord',
            name='donated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่บริจาค'),
        ),
        migrations.AlterField(
            model_name='donationrecord',
            name='donation_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='myapp.donationcase', verbose_name='เคสบริจาค (ถ้ามี)'),
        ),
        migrations.AlterField(
            model_name='donationrecord',
            name='payment_method',
            field=models.CharField(max_length=50, verbose_name='ช่องทางการชำระเงิน'),
        ),
        migrations.AlterField(
            model_name='donationrecord',
            name='slip_image',
            field=models.ImageField(blank=True, null=True, upload_to='donation_slips/', verbose_name='รูปสลิป'),
        ),
        migrations.AlterField(
            model_name='donationrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้บริจาค (ถ้าล็อกอิน)'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='personality',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
