# Generated by Django 5.2.1 on 2025-05-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_conversation_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='interview_datetime',
            field=models.DateTimeField(blank=True, help_text='ผู้ใช้เลือกวันเวลาสำหรับ Video Call กับผู้ประสานงาน', null=True, verbose_name='วันและเวลานัดหมายสัมภาษณ์ (Video Call)'),
        ),
    ]
