# Generated by Django 5.2.1 on 2025-05-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_adoptionapplication_interview_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ (Pending)'), ('approved', 'อนุมัติแล้ว (Approved)'), ('rejected', 'ถูกปฏิเสธ (Rejected)'), ('under_review', 'กำลังตรวจสอบ (Under Review)'), ('canceled', 'ยกเลิกแล้ว (Canceled)')], default='pending', max_length=20, verbose_name='สถานะคำขอ'),
        ),
    ]
