# Generated by Django 5.2.1 on 2025-05-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_adoptionapplication_user_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='user',
        ),
        migrations.AddField(
            model_name='donationcase',
            name='promptpay_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PromptPay ID สำหรับเคสนี้'),
        ),
        migrations.AddField(
            model_name='donationsettings',
            name='default_promptpay_id',
            field=models.CharField(blank=True, help_text='หมายเลข PromptPay หลักของมูลนิธิ หากเคสไม่มี ID ของตัวเอง', max_length=50, null=True, verbose_name='Default PromptPay ID (สำหรับบริจาคทั่วไป)'),
        ),
        migrations.AlterField(
            model_name='donationsettings',
            name='promptpay_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='site_settings/qr_codes/', verbose_name='PromptPay QR Code Image (สำหรับบริจาคทั่วไป)'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
