# Generated by Django 5.2.1 on 2025-05-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_remove_adoptionapplication_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationcase',
            name='promptpay_id',
        ),
        migrations.RemoveField(
            model_name='donationsettings',
            name='default_promptpay_id',
        ),
        migrations.AlterField(
            model_name='donationsettings',
            name='promptpay_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='site_settings/qr_codes/', verbose_name='PromptPay QR Code Image'),
        ),
    ]
