# Generated by Django 5.2.1 on 2025-05-12 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_remove_donationcase_promptpay_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='ข้อความแจ้งเตือน')),
                ('link', models.URLField(blank=True, null=True, verbose_name='ลิงก์ที่เกี่ยวข้อง')),
                ('is_read', models.BooleanField(default=False, verbose_name='อ่านแล้ว')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่สร้าง')),
                ('notification_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='ประเภทการแจ้งเตือน')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับการแจ้งเตือน')),
            ],
            options={
                'verbose_name': 'การแจ้งเตือน',
                'verbose_name_plural': 'การแจ้งเตือนทั้งหมด',
                'ordering': ['-created_at'],
            },
        ),
    ]
