# Generated by Django 5.2.1 on 2025-05-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_alter_pet_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='size',
            field=models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('unknown', 'Unknown')], default='unknown', max_length=10, null=True),
        ),
    ]
